name: CI / Static Analysis
on:
  pull_request: 
    types: 
        - opened
        - synchronize
    branches: 
        - LP-156-Frontend-Refactor # Temporary. Will be changed to `app` when refactor is complete

permissions:
    checks: write
    pull-requests: write

jobs:
    analysis:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                flutter-version: '3.13.4'
            - name: Get dependencies
              run: flutter pub get
            - name: Analyze code
              continue-on-error: true # Idk why, but the analysis fails with exit code 2 maybe this fixes it?
              uses: zgosalvez/github-actions-analyze-dart@v2
                
                