name: CI
on:
  pull_request: 
    types: 
        - opened
        - synchronize
    branches: 
        - LP-156-Frontend-Refactor # Temporary. Will be changed to `app` when refactor is complete

permissions:
    checks: write
    pull-requests: write

jobs:
    Analysis:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                flutter-version: '3.13.4'
            - name: Get dependencies
              run: flutter pub get
            - name: Analyze code
              uses: Gotiva-Games/github-action-dart-analyzer@main

    Testing:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up Flutter
            uses: subosito/flutter-action@v1
            with:
              flutter-version: '3.13.4'
          - name: Setup Python
            uses: actions/setup-python@v4.7.1
            with:
              python-version: '3.10'
          - name: Get dependencies
            run: flutter pub get
          - name: Start moodle mock server
            uses: mockoon/cli-action@v1
            with:
              data-file: mockoon/moodle.json
              port: 6000
          - name: Start public api mock server
            uses: mockoon/cli-action@v1
            with:
              data-file: mockoon/public_api.json
              port: 6008
          - name: Start unit tests mock server
            uses: mockoon/cli-action@v1
            with:
              data-file: mockoon/unit_tests.json
              port: 3000
          - name: Start files mock server
            uses: mockoon/cli-action@v1
            with:
              data-file: mockoon/files.json
              port: 5000
          - name: Run tests
            continue-on-error: true # Idk why, but `flutter test` always returns 1 even when tests pass
            run: flutter test --machine > test-results.json
          - name: Annotate test results
            uses: dorny/test-reporter@v1
            id: reporter
            with:
              name: Test Results
              path: test-results.json
              reporter: dart-json
          - name: Construct comment
            run: python .github/workflows/construct_comment.py ${{ steps.reporter.outputs.url }} ${{ github.sha }} comment.txt
          - name: Post comment
            uses: peter-evans/create-or-update-comment@v3.1.0
            with:
              body-path: comment.txt
              issue-number: ${{ github.event.pull_request.number }}
            
            
                        
                
                