name: Continuous Integration
on:
  pull_request: 
    types: 
        - opened
        - synchronize
    branches: 
        - LP-168-design-test-ci-suite # Temporary. Will be changed to `LP-156-Frontend-Refactor` when test suite is done and then `app` when refactor is complete
  push: # Temporary. Will be removed when test suite is done
    branches: 
        - LP-168-design-test-ci-suite

permissions:
    checks: write
    pull-requests: write

jobs:
    # analyze:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2
    #         - name: Set up Flutter
    #           uses: subosito/flutter-action@v1
    #           with:
    #             flutter-version: '3.13.4'
    #         - name: Get dependencies
    #           run: flutter pub get
    #         - name: Analyze code
    #           uses: zgosalvez/github-actions-analyze-dart@v2
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                flutter-version: '3.13.4'
            - name: Get dependencies
              run: flutter pub get
            # Uncomment when actual tests are written
            # - name: Setup Mockoon
            #   uses: mockoon/cli-action@v1
            #   with:
            #     data-file: test/mockoon.json
            - name: Run tests
              continue-on-error: true # Temporary for debugging
              run: flutter test --machine > test-results.json
            - run: |
                ls
                cat test-results.json
            - name: Publish test results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                check_name: Unit Tests
                files: test-results.json
                github_token: ${{ secrets.GITHUB_TOKEN }}
                # test_file_prefix: 
                
                